// astro-frontend/src/components/Likes.svelte
<script lang="ts">
  export let likes: any[];
  export let leftToRight = false;

  $: doubleLikes = [...likes, ...likes];
</script>

<div
  class="personal-text w-full flex {leftToRight
    ? 'translate-x-full scrollTextLeftToRight'
    : '-translate-x-full scrollTextRightToLeft'} "
>
  {#each doubleLikes as like, i}
    <p
      class="font-bold lg:text-7xl md:text-7xl text-4xl uppercase hover:-translate-y-4 transition duration-200 ease-out {i %
        2 ==
      0
        ? 'different-font'
        : ''}"
    >
      {like.name}
    </p>
  {/each}
</div>

<style lang="scss">
  .different-font {
    font-family: "Montagu Slab", serif;
    font-weight: 300;
  }

  .scrollTextRightToLeft {
    animation: scrollRightToLeft 20s linear infinite;
  }

  @keyframes scrollRightToLeft {
    0% {
      transform: translateX(-100%);
    }
    100% {
      transform: translateX(0);
    }
  }

  .scrollTextLeftToRight {
    animation: scrollLeftToRight 20s linear infinite;
  }

  @keyframes scrollLeftToRight {
    0% {
      transform: translateX(0%);
    }
    100% {
      transform: translateX(-100%);
    }
  }
</style>

// nuxt-frontend/components/Likes.vue
<script setup lang="ts">
import gsap from "gsap";
import Context = gsap.Context;

const props = defineProps<{
  likes: any[],
  leftToRight: boolean
}>();

const doubleLikes = [...props.likes, ...props.likes]

</script>

<template>
  <div
      :class="`personal-text  w-full flex ${leftToRight
    ? 'left-to-right -translate-x-full'
    : 'right-to-left'}`"
  >

    <p
        v-for="(like, i) in doubleLikes"
        :class="`font-bold lg:text-7xl md:text-7xl text-4xl uppercase hover:-translate-y-4 transition duration-200 ease-out ${i %
        2 ===
      0
        ? 'font-light'
        : ''}`"
    >
      {{ like.name }}
    </p>
  </div>
</template>

<style scoped>
</style>
